version: '2'

services:
  mydatastore:
    image: google/cloud-sdk:latest
    hostname: mydatastore
    expose:
      - 8000
    command: gcloud beta emulators datastore start --project=pi-docker --host-port mydatastore:8000 --no-store-on-disk

  mytest:
    image: appropriate/curl
    command: curl mydatastore:8000
    depends_on:
      - mydatastore
